{% set version = "1.4.0" %}

package:
  name: r-rsaga
  version: {{ version.replace("-", "_") }}

source:
  url:
    - http://cran.r-project.org/src/contrib/RSAGA_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/RSAGA/RSAGA_{{ version }}.tar.gz
  sha256: 0563c98547f520212475a3b9783d3844d5575858d9284eca0494fcd14ecfb155

build:
  noarch: generic
  number: 2
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-gstat
    - r-shapefiles
    - r-plyr
    - r-stringr
    - r-magrittr
  run:
    - r-base
    - r-gstat
    - r-shapefiles
    - r-plyr
    - r-stringr
    - r-magrittr

test:
  commands:
    - R -e "library('RSAGA')"

about:
  home: https://cran.r-project.org/web/packages/RSAGA/index.html
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Provides access to geocomputing and terrain analysis functions of the geographical information system (GIS) 'SAGA' (System for Automated Geoscientific Analyses) from within R by running the command  line version of SAGA. This package furthermore provides several R functions for handling ASCII grids, including
    a flexible framework for applying local functions (including predict methods of fitted models) and focal functions to multiple grids. SAGA GIS is available under GPLv2 / LGPLv2 licence from http://sourceforge.net/projects/saga-gis/.

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r
