appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PqQqxICUiIx9CGJZfdTrk65OT8IhSwLzobqTTuYatS34c1OVhLDvf8Aj7qqF8WEKV7mh+Eayn8cIJIia1x6yXPr5qiknW1yL4LQRbUELHvoTmxLGukLHKRvSXSEc1oyqUhIr9yHNSkmSrKT5R19qQgHJCEKQSbUN9f5DJkUqOnAm9Tmf9Qzrpl7K9EClOyF+9g8kldYfhmgDhvxxH83QwkMBwYfQjtK0y8FQrAe9nzATXQlC4SL3NyZEqNPYHHQ4iG8SYZo9v8o++zAeTKhNCy2JHKiZ8XkEhNrga7+UGPJlFUPTvg7PRfCtBLlm7DtVYb9cQogAFpv910UuTVbMpSvTpj/g3xAcOnLy0fo9UvXBMH/5EH+lMgeKqmfv5Lh0mDIh0FPdLmTqLiobx9Id23W5Q1Nr2ZTOq/Us2Ew+RxsCEV5OOoRp79uTdrv+aner2kO3Sek3oRY9g3YMXOwVZTCUn1NzvLsN3ayHHsGn86vrAnlstAlAxf8l+8bDWszq7+3O5V/qnOFxrjEomEIOd93cavrWCSXiJB49WE9vHboDoCnSzlpkr13bwJqHCep1Rts9B2WtYHs8SCP985Q78bZgOCLTq5JbYGxYvDRyQtpAbJ3/7+24DwXcVCziF2NpCBKX2Jevjd7iCMZOhoik7staMnPxz3bDJB4lu+dQ79o=
conda_forge_output_validation: true
